platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'YALSideMenu'
#TTPL API manager
pod 'TTPLAPIManager', :git => 'https://github.com/iosttpl/TTPLAPIManager.git'

# Keyboard avoiding for autolayout
pod 'IQKeyboardManager'